preload = ~/.dotfile/wallpapers/sunset.png


wallpaper {
    monitor = DP-2
    path = ~/.dotfile/wallpapers/sunset.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1 
    path = ~/.dotfile/wallpapers/sunset.png
    fit_mode = cover
}

